---
- name: Example Playbook
  hosts: web_servers
  tasks:
     - name: Update package cache
       apt:
          update_cache: yes
       become: yes

     - name: Ensure Nginx is installed
       apt:
          name: nginx
          state: present
       become: yes

     - name: Ensure Nginx is running
       service:
          name: nginx
          state: started
       become: yes
