---
- name: Example Playbook
  hosts: 
    - web_servers
  become: yes
  tasks:

    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Gather the rpm package facts
      package_facts:
        manager: auto

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg
        - nginx
        - docker.io
        - docker-compose
      when: "item not in ansible_facts.packages"

